### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [CarlosCala/Backend-Proyecto3-RollingPizza#5]
Buenas! como va? encontre algunos comentarios en el codigo,
![image](https://user-images.githubusercontent.com/53904695/232622375-7dbb287f-4da6-44cf-a6a9-8080522694d8.png)
Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by CarlosCala** [comment]
Pase a eliminar los comentarios.
