### ISSUE TITLE
Eliminar console.log

### ISSUE THREAD

**Issue by Nidev-lab** [CarlosCala/Backend-Proyecto3-RollingPizza#6]
Buenas! encontre algunos console.log que no deberian estar..

![image](https://user-images.githubusercontent.com/53904695/232623073-a0a74ed5-148c-4fc3-a9bf-6bea3f7f3d6e.png)

los console.log en los catch o en donde necesitemos mostrar un error a los usuario por consola, deberian ser console.error

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by CarlosCala** [comment]
Pase a eliminar los console.log innecesarios, y cambiar por console.error los que se encontraban en catch
